### ISSUE TITLE
`spyndex` breaks with `earthengine-api==0.1.365`

### ISSUE THREAD

**Issue by LaurentBerder** [awesome-spectral-indices/spyndex#19]
I'm struggling to get `spyndex` to work on my machine.
The installation with `pip install spyndex` works like a charm, but when I run `import spyndex` in python, I invariably get errors relating to ee.

So I'm wondering what version of earthengine-api you're based on, as all the versions I've tried so far result in various errors. Here what I get with the latest (earthengine-api==0.1.365
```python
Traceback (most recent call last):
  File "python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\spyndex\__init__.py", line 8, in <module>
    from .axioms import bands, constants, indices
  File "python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\spyndex\axioms.py", line 3, in <module>
    from .spyndex import computeIndex
  File "python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\spyndex\spyndex.py", line 7, in <module>
    import ee
  File "python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\ee\__init__.py", line 15, in <module>
    from ee import batch
  File "python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\ee\batch.py", line 15, in <module>
    from ee import data
  File "python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "venv\lib\site-packages\ee\data.py", line 542, in <module>
    def listAssets(params: dict[str, Any]) -> dict[str, List[Any]]:
TypeError: 'type' object is not subscriptable
```

I'm working in Python 3.8.10.

**Comment by davemlz** [comment]
Thank you for noticing!

This also answers the question of #17.

I'll work on it ;)
